name: Build and Push CVAT Images to GCR

on:
  push:
    branches:
      - develop  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use GCR
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > ${HOME}/gcloud-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
          gcloud auth configure-docker

      - name: Build Docker images with Docker Compose
        run: |
          docker-compose build

      - name: Tag and Push Docker images to GCR
        run: |
          for service in $(docker-compose config --services); do
            docker tag ${service} gcr.io/${{ secrets.GCP_PROJECT_ID }}/${service}:${{ github.sha }}
            docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${service}:${{ github.sha }}
          done

